### ISSUE TITLE
Does not work, get a line 32, curling the script does not work. i think its looking for specific named files? basensp? updatensp?

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [Damaj301damaj-lol/termux-update-nsp#1]
do I simply just follow your instructions? How do I use it ...since there are no commands I see for updating nsp, also folks over on sky discord are wondering if dlc support is coming aka not just patch base but patch base with update and dlc, also script no work:
line 32, curling the script does not work.
i think its looking for specific named files?
basensp? updatensp?

**Comment by Damaj301damaj-lol** [comment]
Fixed, you may ```git pull``` and try it again, also this is just a rewrite of the download script xq, not the patching script, that stayed the same
